### Get products
GET http://localhost:8080/products?page=1&limit=4

### Get products
GET http://localhost:8080/products?page=2&limit=4

### Get products
GET http://localhost:8080/products?page=3&limit=4